<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ihHHRMT' shared service.

return $this->privates['.service_locator.ihHHRMT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PostController::index' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\PostController::remove' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController::show' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\PostController:index' => ['privates', '.service_locator.bY1MqeR', 'get_ServiceLocator_BY1MqeRService.php', true],
    'App\\Controller\\PostController:remove' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\PostController:show' => ['privates', '.service_locator.TwhmRPL', 'get_ServiceLocator_TwhmRPLService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\PostController::index' => '?',
    'App\\Controller\\PostController::remove' => '?',
    'App\\Controller\\PostController::show' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\PostController:index' => '?',
    'App\\Controller\\PostController:remove' => '?',
    'App\\Controller\\PostController:show' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
