#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#horse_route:
#    path:   /category
#    controller: App\Controller\PostController::index 

category_route:
    path:       /category/{cat}
    controller: App\Controller\PostController::findByCat