<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIbETdTZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIbETdTZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIbETdTZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIbETdTZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIbETdTZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IbETdTZ',
    'container.build_id' => 'cdd8f5ec',
    'container.build_time' => 1573637930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIbETdTZ');
