<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPsTAWv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPsTAWv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPsTAWv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPsTAWv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFPsTAWv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FPsTAWv',
    'container.build_id' => 'fcec0f16',
    'container.build_time' => 1573643874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPsTAWv');
