<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xg8qfi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xg8qfi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6xg8qfi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6xg8qfi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6xg8qfi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6xg8qfi',
    'container.build_id' => '858dd5a0',
    'container.build_time' => 1573727023,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xg8qfi');
